apiVersion: v1
kind: Service
metadata:
  name: locust-master
  labels:
    app: locust
    role: master
spec:
  selector:
    app: locust
    role: master
  ports:
    - name: locust-master-8089
      protocol: TCP
      port: 8089
    - name: locust-master-5557
      protocol: TCP
      port: 5557
    - name: locust-master-5558
      protocol: TCP
      port: 5558
---
apiVersion: v1
kind: Service
metadata:
  name: locust-master-lb
  labels:
    app: locust
    role: master
spec:
  selector:
    app: locust
    role: master
  type: LoadBalancer
  ports:
    - port: 8089
