apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-standalone
  labels:
    app: locust
    role: standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
      role: standalone
  template:
    metadata:
      labels:
        app: locust
        role: standalone
    spec:
      containers:
        - name: locust-standalone
          image: kota661/locust
          args: 
            - -f
            - locust_files/tasks_index.py
            - --host=$(TARGET_HOST)
          env:
            - name: TARGET_HOST
              value: http://example.com
          ports:
            - containerPort: 8089
            - containerPort: 5557
            - containerPort: 5558
---
apiVersion: v1
kind: Service
metadata:
  name: locust-standalone
  labels:
    app: locust
    role: standalone
spec:
  selector:
    app: locust
    role: standalone
  type: LoadBalancer
  ports:
    - port: 8089
